---
abstract: 'Perl module info command line.'
author:
  - 'Thiago Rondon <thiago@nsms.com.br>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-pmodinfo
requires:
  Config: 0
  DateTime: 0
  ExtUtils::Installed: 0
  File::Which: 0
  File::stat: 0
  FindBin: 0
  Getopt::Long: 0
  LWP::Simple: 0
  Module::CoreList: 0
  Module::Metadata: 0
  Parse::CPAN::Meta: 0
resources:
  bugtracker: http://github.com/maluco/App-pmodinfo/issues
  repository: git://github.com/maluco/App-pmodinfo
version: 0.08
